# Generated by Django 4.0.3 on 2022-06-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0003_answer_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_key', models.CharField(max_length=12)),
            ],
        ),
    ]
